### ISSUE TITLE
Python bindings installation

### ISSUE THREAD

**Issue by lnotspotl** [mayataka/robotoc#102]
Hello, 

first of all, I'd like to say that what you're doing is amazing. I really like this project a simply reading through the code teaches me a lot.

I wanted to play around with the python bindings the other day, so I followed the installation procedure and installed everything according to the installation guide. However, when I try to import robotoc, the python interpreter complains that there's no robotoc.robot.contact_status module.

Do you know, why this could be?

Thanks.
![image](https://user-images.githubusercontent.com/82883398/147886305-96d02d99-60d3-4862-a080-8ddd48957fd7.png)

**Comment by mayataka** [comment]
Hi, 

Thank you for being interested in this project.
This problem sometimes happens to me, too. Currently, I cannot get the cause.
In my case, I can install the Python bindings by doing
```
cmake ..
```
again at the `build` directory. Then `make install` may install the Python bindings.

**Comment by lnotspotl** [comment]
Yep, that worked well. Thank you.

Once again, thank you for making all of this open-source, it's so much fun to learn from this project.

**Comment by mayataka** [comment]
I'll keep this issue open because the same problem can occur for others.
