### ISSUE TITLE
CMake version must be newer than 3.11

### ISSUE THREAD

**Issue by ssr-yuki** [mayataka/robotoc#107]
Hi. I found that this software requires CMake newer than 3.11 for the python binding.

As shown below, in building the python binding, CMake uses `FetchContent` module.
https://github.com/mayataka/robotoc/blob/c10714ea1be4ab5814ce9a0636b5a726a1ed901b/bindings/python/CMakeLists.txt#L1-L10

While this `FetchContent` module appears after version 3.11 (please see the 5th content of the [CMake 3.11 Release Notes / Modules](https://cmake.org/cmake/help/v3.11/release/3.11.html#modules)), the version requirement is still >=3.1.
https://github.com/mayataka/robotoc/blob/c10714ea1be4ab5814ce9a0636b5a726a1ed901b/CMakeLists.txt#L1

I recommend you to set the minimum required version to 3.11 or higher

---

In my environment (Ubuntu 18.04 + default CMake (3.10.2)), a CMake error occurs (the error message is shown below), and updating CMake to the latest (3.22.2) resolves it.

```
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DOPTIMIZE_FOR_NATIVE=ON
-- pinocchio FOUND. pinocchio at /opt/openrobots/lib/libpinocchio.so
-- boost_filesystem FOUND. boost_filesystem at /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
-- boost_serialization FOUND. boost_serialization at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- boost_system FOUND. boost_system at /usr/lib/x86_64-linux-gnu/libboost_system.so
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   serialization
--   system
-- hpp-fcl FOUND. hpp-fcl at /opt/openrobots/lib/libhpp-fcl.so
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   chrono
--   serialization
--   system
-- Default C++ standard: 201402
-- C++ standard sufficient: Minimal required 11, currently defined: 11
-- C++ standard sufficient: Minimal required 11, currently defined: 11
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
CMake Error at bindings/python/CMakeLists.txt:1 (include):
  include could not find load file:
    FetchContent

CMake Error at bindings/python/CMakeLists.txt:2 (FetchContent_GetProperties):
  Unknown CMake command "FetchContent_GetProperties".

-- Configuring incomplete, errors occurred!
```

References: [CMake error "include could not find load file: FetchContent" - stackoverflow](https://stackoverflow.com/questions/55746663/cmake-error-include-could-not-find-load-file-fetchcontent)

**Comment by mayataka** [comment]
Thank you for reporting the issue.
It is a title a bit curious for me because CI for Ubuntu 18.04 passes with python bindings. (CMake is installed with `build-essentials`)
I'll consider replacing `FetchContent` with `submodule` of pybind11.
