### ISSUE TITLE
C++ visualization not working 

### ISSUE THREAD

**Issue by syangav** [mayataka/robotoc#128]
Hi Sotaro, 

Thanks for open-sourcing such nice software! 

When I am playing with your code, I bumped into a visualization error in C++. To be more exact, I would like to build the cpp files in examples/anymal with ENABLE_VIEWER to be 'ON' from the CMakeLists.txt to see the visualization effect. All examples (trot, crawl, pace, bounce, jump, run, jump_sto) can be successfully built. However, when executing, the following messages jumped out: 

Failed in connecting to CORBA!!
omniORB: (0) 2022-08-24 15:51:55.371327: Error: the application attempted to invoke an operation on a nil reference.
terminate called after throwing an instance of 'CORBA::INV_OBJREF'
Aborted (core dumped)

After some investigation, I realized that it is at [this line](https://github.com/mayataka/robotoc/blob/6c0067ae7ece43fad67392fda7416ba1e9c9d5cc/src/utils/trajectory_viewer.cpp#L163) where the pinocchio::gepetto::Viewer cannot be initialized, which is pretty weird, because model_ and vmodel_  are all well-initialized according to my understanding. I did some search, but sadly found nothing valuable for debugging. 

P.S. I have installed [gepetto-viewer-corba](https://github.com/Gepetto/gepetto-viewer-corba.git) and [pinocchio-gepetto-viewer](https://github.com/stack-of-tasks/pinocchio-gepetto-viewer) properly. The python visualization (from jupyter notebook) works well. 

Any help are greatly appreciated! And thanks for your time in advance. 

Best regards, 
Shaohui Yang

**Comment by mayataka** [comment]
Hi @syangav 

Thank you for being interested in this repo!
To use the C++ visualizer, you have to launch `gepetto-viewer` in another terminal via
```
gepetto-gui
```
Then the C++ visualizer will successfully work.
The Python  visualizer is more convenient because it launches the `gepetto-gui` inside of the class.

**Comment by syangav** [comment]
Thanks for your fast reply and nice easy fix! Wish you a good night! 

If you think it's necessary, this issue can be kept open for helping others, just like the previous python binding [one](https://github.com/mayataka/robotoc/issues/102#issue-1092078854).

**Comment by mayataka** [comment]
C++ visualizer is removed with #135  as it is really unuseful. 
Please use python visualizer instead.
