### ISSUE TITLE
Controlling joint positions

### ISSUE THREAD

**Issue by sharathmatada** [mayataka/robotoc#134]
Hi, 
Can you guide me on how I can go about simulating a quadruped for which I have an array of joint angle values? Are there any examples that I can look at to better understand this? 
Thanks

**Comment by mayataka** [comment]
Hi @sharathmatada, 
In the simulation in robotoc (`robotoc_sim` Python module), we assume that we can only control the joint torques and cannot control the joint positions directly.

**Comment by sharathmatada** [comment]
Thank you for your quick response! So we can only decide parameters of gaits such as crawl, trot, pace etc in robotoc right? Is this mainly because these gaits provide a definite contact sequence? If I were to give arbitrary set of joint angles the contact sequence would be unknown. Is my understanding right? I'm thinking in this direction one of the assumptions in your optimal control formulation was the contact sequence is given (Referring to your paper titled " Whole-body model predictive control with rigid contacts
via online switching time optimization")

**Comment by mayataka** [comment]
> So we can only decide parameters of gaits such as crawl, trot, pace etc in robotoc right?

Actually you can also design more variety of gaits by designing the contact sequence and cost function by yourself. Please regard our MPC implementations just as examples of how to use `robotoc::OCPSolver` to implement MPC.

> I'm thinking in this direction one of the assumptions in your optimal control formulation was the contact sequence is given.

Your understanding is right. Basically, we assume that there is a given contact sequence.
