### ISSUE TITLE
MJtJinv matrix is not full of rank when robot has multiple contacts 

### ISSUE THREAD

**Issue by YechenZhou** [mayataka/robotoc#138]
Thank you for such an excellent code. However, when I apply your code to the OCP of my snake robot, snake robot makes multiple contacts with the ground and Jacobian matrix is singular, then MJtJinv matrix can not be evaluated well. I try use pseudoinverse of JMinvJt to evaluate  MJtJinv matrix, it also doesn't work because of the divergence. Could you give me some suggestions? Thanks.

related code gives as follows:
 `d.dbetamu().noalias()  = - data.MJtJinv() * data.laf();`

**Comment by jcarpent** [comment]
This paper of mine will solve your issue: https://hal.inria.fr/hal-03271811/

**Comment by YechenZhou** [comment]
Thanks.

**Comment by YechenZhou** [comment]
> This paper of mine will solve your issue: https://hal.inria.fr/hal-03271811/

Is there some open-source code about "Proximal and Sparse Resolution
of Constrained Dynamic Equations" paper ?
